### ISSUE TITLE
Such indie, not much rss?

### ISSUE THREAD

**Issue by nitinthewiz** [Kongaloosh/blog-a-loosh#62]
Hey Alex!

I see your site and I raise you an Issue about lack of RSS or JSON feed!

I know, I know... It's not strictly something that's useful to you, but it makes it so much easier for Luddites like me to follow you on our feed readers... 

Could you please add something like that? Or would you be open to a PR?

**Comment by Kongaloosh** [comment]
Hey, I'd be totally open to PRs, though it might be challenging making it through my spaghetti-code framework.

If it makes it easier for others, I'll put it on the stack of things to do!

**Comment by nitinthewiz** [comment]
wow, you weren't joking when you said spaghetti code!

I'm working through it and hopefully, without touching a lot of things, I should be able to produce a simple template for feeds and an app route for /json.feed and /rss.xml

**Comment by Kongaloosh** [comment]
If you want answers about structure and content, feel free to ping me on irc at freenode.
Is there a way I can help you with this?

**Comment by nitinthewiz** [comment]
Sent you a PR... I was able to work through your code with ease, actually...

The setup was a pain. The fact that I'm on Windows didn't matter, but the requirements text wasn't useful. I had to run the main file over and over to see what all was missing, like flask, bs4, rdflib, slugify (which is really cool!)

Then I got the error that there are no tables, so I found your .sql file and ran that using sqlitebrowser.org and then I was good to go-ish. I also had to fight a little with the config file as some code somewhere expects sections for GeoNamesUsername and PersonalInfo in there, but they're not mentioned in the config.ini file per se.

Other than that, it was a breeze! 😄

**Comment by Kongaloosh** [comment]
Thanks for the Pull Request! I'll merge it to the main branch and set it up on my server this evening. 

Also, I appreciate the heads-up on the requirements and the setup information. I'm thinking of making a simple wizard script which takes care of this for people like you---filling out the config file, etc. If you have feelings on how that could be streamlined for others, I'd love your feedback. On closer inspection, I see my config is out of date, cheers.

Any criticism on structure would be appreciated. I started this with zero knowledge of web architecture, so I'm still trying to figure out the principles.

**Comment by nitinthewiz** [comment]
Hmmm... I don't have any criticism of the structure. I'm still very much an infant when it comes to web dev. I just understand what works, not what's *right*, and I think that's how much of the Internet works.

Of course, the usual recommendations which everyone gives, as I've received them too - 

The site name, the site URL, the author name etc. should be in the config and never hardcoded. In the JSON and RSS code, I've had to hard code some things. When you're eventually going through it to make it cleaner, it would be nice to replace every place you've mentioned your name in the code with auhor.full_name

A wizard script makes sense, but don't try to make it perfect for everyone. Make it so that it works on DigitalOcean and that should be that...

**Comment by Kongaloosh** [comment]
Thanks @nitinthewiz. I've merged the changes and it's up and running.

**Comment by nitinthewiz** [comment]
Yay! I subscribed to your rss feed! 😄
